In [1]:
import tensorflow as tf
tf.__version__

'1.15.0'

In [4]:
m1 = tf.constant([[1, 2], [3, 4]])
m2 = tf.constant([[-1, 3], [4, 2]])

In [5]:
# matmul (matrices multiplication) -> tf method to multiply matrices
#matmul(m1, m2) != m1 * m2
multiplication = tf.matmul(m1, m2)

In [6]:
with tf.Session() as sess:
    print('m1:\n',sess.run(m1))
    print('m2:\n',sess.run(m2))    
    print('matmul m1 m2:\n',sess.run(multiplication))    

m1:
 [[1 2]
 [3 4]]
m2:
 [[-1  3]
 [ 4  2]]
matmul m1 m2:
 [[ 7  7]
 [13 17]]


In [7]:
multiplication2 = tf.matmul(m2, m1)

In [10]:
with tf.Session() as sess:
    print('m1:\n',sess.run(m1))
    print('m2:\n',sess.run(m2))    
    print('matmul m2 m1:\n',sess.run(multiplication2))    

m1:
 [[1 2]
 [3 4]]
m2:
 [[-1  3]
 [ 4  2]]
matmul m2 m1:
 [[ 8 10]
 [10 16]]


In [12]:
m3 = tf.constant([[2, 3], [0, 1], [-1, 4]])
m4 = tf.constant([[1, 2, 3], [-2, 0, 4]])
multiplication3 = tf.matmul(m3, m4)

In [13]:
with tf.Session() as sess:
    print('m3:\n',sess.run(m3))
    print('m4:\n',sess.run(m4))    
    print('matmul m3 m4:\n',sess.run(multiplication3))    

m3:
 [[ 2  3]
 [ 0  1]
 [-1  4]]
m4:
 [[ 1  2  3]
 [-2  0  4]]
matmul m3 m4:
 [[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]
