In [2]:
import tensorflow as tf

In [3]:
# placeholders are variables that have no data and are not initialized
# just hold the type of data that will be passed
p = tf.placeholder('float', None) #type and size(None for "any")

In [5]:
operation = p + 2

In [7]:
with tf.Session() as sess:
    # sess.run(operation) #doesn't work because a value must feed the placeholder tensor
    result = sess.run(operation, feed_dict={p: [1, 2, 3]})
    print(result)

[3. 4. 5.]


In [19]:
p2 = tf.placeholder('float', [None, 5])
operation2 = p2 * 5

In [20]:
with tf.Session() as sess:
    data = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
    result2 = sess.run(operation2, feed_dict={p2: data})
    print(result2)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
