<h1>Multiple Linear Regression:</h1><br>
<div>y = b0 + b1 * x1 + b2 * x2 + ... + bn * xn</div>
<h2>Goal: Use multiple parameters of the house to predict its value</h2> 

In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
# see columns names
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
util_columns = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
util_columns

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv('house_prices.csv', usecols=util_columns)

In [6]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

<h1>scaling</h1>
<h2>standardzation -> put all values in same scale</h2>
<h2>normalization -> put all values in between 0 and 1</h2>

In [7]:
# normalization method
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']]) # all x axis parameters

In [8]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [11]:
# separating x and y
x = base.drop('price', axis = 1)
y = base.price

In [12]:
x.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [13]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [14]:
type(y)

pandas.core.series.Series

In [15]:
predictors_columns = util_columns[1:17]
predictors_columns

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [16]:
import tensorflow as tf

In [17]:
# definition of feature columns
# feature columns are the columns of input for the model
columns = [tf.feature_column.numeric_column(key=c) for c in predictors_columns ]

In [18]:
columns[10]

NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [20]:
print(f"x_train: {x_train.shape}, x_test: {x_test.shape}")

x_train: (15129, 16), x_test: (6484, 16)


In [21]:
print(f"y_train: {y_train.shape}, y_test: {y_test.shape}")

y_train: (15129,), y_test: (6484,)


In [22]:
train_func = tf.estimator.inputs.pandas_input_fn(x = x_train,
                                                y = y_train,
                                                batch_size=32,
                                                num_epochs=None, 
                                                shuffle=True
                                                )

In [23]:
test_func = tf.estimator.inputs.pandas_input_fn(x = x_test,
                                                y = y_test,
                                                batch_size=32,
                                                num_epochs=10000, 
                                                shuffle=True
                                                )

In [24]:
regressor = tf.estimator.LinearRegressor(feature_columns=columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\GABRIE~1.CAL\\AppData\\Local\\Temp\\tmpcd8ebf_y', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000018B6DD90F48>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


<h1>ESTIMATORS METHODS:</h1>

In [25]:
regressor.train(input_fn=train_func, steps=10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use `tf.cast` instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\GABRIE~1.C

INFO:tensorflow:loss = 0.03307987, step = 5001 (0.182 sec)
INFO:tensorflow:global_step/sec: 500.2
INFO:tensorflow:loss = 0.009426007, step = 5101 (0.201 sec)
INFO:tensorflow:global_step/sec: 497.857
INFO:tensorflow:loss = 0.017963938, step = 5201 (0.200 sec)
INFO:tensorflow:global_step/sec: 480.997
INFO:tensorflow:loss = 0.00982089, step = 5301 (0.208 sec)
INFO:tensorflow:global_step/sec: 530.443
INFO:tensorflow:loss = 0.012402082, step = 5401 (0.189 sec)
INFO:tensorflow:global_step/sec: 498.836
INFO:tensorflow:loss = 0.015466753, step = 5501 (0.200 sec)
INFO:tensorflow:global_step/sec: 540.9
INFO:tensorflow:loss = 0.011497684, step = 5601 (0.185 sec)
INFO:tensorflow:global_step/sec: 548.229
INFO:tensorflow:loss = 0.009364385, step = 5701 (0.181 sec)
INFO:tensorflow:global_step/sec: 527.732
INFO:tensorflow:loss = 0.009881759, step = 5801 (0.189 sec)
INFO:tensorflow:global_step/sec: 556.59
INFO:tensorflow:loss = 0.020865088, step = 5901 (0.181 sec)
INFO:tensorflow:global_step/sec: 516.7

In [26]:
training_metrics = regressor.evaluate(input_fn=train_func, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2021-12-09T16:12:36Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\GABRIE~1.CAL\AppData\Local\Temp\tmpcd8ebf_y\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2021-12-09-16:12:53
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007416336, global_step = 10000, label/mean = 0.060978822, loss = 0.023732275, prediction/mean = 0.05783789

In [27]:
test_metrics = regressor.evaluate(input_fn=test_func, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2021-12-09T16:12:54Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\GABRIE~1.CAL\AppData\Local\Temp\tmpcd8ebf_y\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2021-12-09-16:13:11
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0006556133, global_step = 10000, label/mean = 0.061036903, loss = 0.020979626, prediction/mean = 0.05783444

In [28]:
training_metrics

{'average_loss': 0.0007416336,
 'label/mean': 0.060978822,
 'loss': 0.023732275,
 'prediction/mean': 0.057837892,
 'global_step': 10000}

In [29]:
test_metrics

{'average_loss': 0.0006556133,
 'label/mean': 0.061036903,
 'loss': 0.020979626,
 'prediction/mean': 0.057834446,
 'global_step': 10000}

In [30]:
# values for prediction, taken from test matrix
prediction_func = tf.estimator.inputs.pandas_input_fn(x = x_test, shuffle=False)

In [31]:
# predict values from prediction function
predictions = regressor.predict(input_fn=prediction_func)

In [32]:
list(predictions)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\GABRIE~1.CAL\AppData\Local\Temp\tmpcd8ebf_y\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.03733932], dtype=float32)},
 {'predictions': array([0.04779013], dtype=float32)},
 {'predictions': array([0.05830723], dtype=float32)},
 {'predictions': array([0.05356606], dtype=float32)},
 {'predictions': array([0.08255579], dtype=float32)},
 {'predictions': array([0.02068799], dtype=float32)},
 {'predictions': array([0.05263051], dtype=float32)},
 {'predictions': array([0.06351908], dtype=float32)},
 {'predictions': array([0.05256734], dtype=float32)},
 {'predictions': array([0.04480755], dtype=float32)},
 {'predictions': array([0.02189144], dtype=float32)},
 {'predictions': array([0.0986115], dtype=float32)},
 {'predictions': array([0.04787624], dtype=float32)},
 {'predictions': array([0.05224264], dtype=float32)},
 {'predictions': array([0.04479624], dtype=float32)},
 {'predictions': array([0.03898488], dtype=float32)},
 {'predictions': array([0.02827609], dtype=float32)},
 {'predictions': array([0.06220165], dtype=float32)},
 {'predictions': array([0.061

In [33]:
prediction_values = []
for p in regressor.predict(input_fn=prediction_func):
    prediction_values.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\GABRIE~1.CAL\AppData\Local\Temp\tmpcd8ebf_y\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [34]:
prediction_values

[array([0.03733932], dtype=float32),
 array([0.04779013], dtype=float32),
 array([0.05830723], dtype=float32),
 array([0.05356606], dtype=float32),
 array([0.08255579], dtype=float32),
 array([0.02068799], dtype=float32),
 array([0.05263051], dtype=float32),
 array([0.06351908], dtype=float32),
 array([0.05256734], dtype=float32),
 array([0.04480755], dtype=float32),
 array([0.02189144], dtype=float32),
 array([0.0986115], dtype=float32),
 array([0.04787624], dtype=float32),
 array([0.05224264], dtype=float32),
 array([0.04479624], dtype=float32),
 array([0.03898488], dtype=float32),
 array([0.02827609], dtype=float32),
 array([0.06220165], dtype=float32),
 array([0.06153546], dtype=float32),
 array([0.0760165], dtype=float32),
 array([0.03592505], dtype=float32),
 array([0.06830356], dtype=float32),
 array([0.03425644], dtype=float32),
 array([0.05562875], dtype=float32),
 array([0.09061535], dtype=float32),
 array([0.01971845], dtype=float32),
 array([0.12983973], dtype=float32),
 ar

In [35]:
import numpy as np
prediction_values = np.asarray(prediction_values).reshape(-1, 1)

In [36]:
type(prediction_values)

numpy.ndarray

In [37]:
prediction_values = scaler_y.inverse_transform(prediction_values)
prediction_values

array([[359712.34],
       [439399.78],
       [519592.62],
       ...,
       [724325.94],
       [182890.17],
       [367501.8 ]], dtype=float32)

In [38]:
y_test

14528    0.028721
8399     0.056656
17239    0.079344
2637     0.060459
16870    0.085246
           ...   
2805     0.040656
17798    0.026230
8235     0.096393
998      0.015075
9331     0.025377
Name: price, Length: 6484, dtype: float64

In [39]:
y_test.shape

(6484,)

In [40]:
y_test2 = y_test.values.reshape(-1,1)
y_test2.shape

(6484, 1)

In [41]:
y_test2 = scaler_y.inverse_transform(y_test2)
y_test2

array([[294000.],
       [507000.],
       [680000.],
       ...,
       [810000.],
       [189950.],
       [268500.]])

In [42]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test2, prediction_values)

In [43]:
mae

127076.39137295364